version: '3.8'

services:
  mysql_perf_monitor:
    build: .
    container_name: mysql_perf_monitor
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "tail -n 100 /app/logs/mysql_perf_reporter.log | grep 'HEARTBEAT' | grep $(date +%Y-%m-%d) | grep $(date +%H:%M | cut -c1-4) || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  watchdog:
    build: .
    container_name: watchdog
    command: python watchdog.py
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mysql_perf_monitor
    restart: unless-stopped 